import Head from "next/head";
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
    return (
        <div>
            <Head>
                <title>FUDO</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/Logo.png" />
            </Head>
            <Component {...pageProps} />
        </div>
    );
}

export default MyApp;
