import Head from "next/head";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>FUDO</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Body */}
            <main>
                <h1>Hello</h1>
            </main>
        </div>
    );
}
